language: julia

os:
  - linux
  - osx
  # - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
    # - os: windows
  allow_failures:
    - julia: nightly

notifications:
  email: true

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("SOFA"; coverage=true)'
  
after_success:
  # Install required packages for coverage and documentation
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'

  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'  

  # Build and deploy documentation
  - julia --project ./docs/make.jl
